
name: AzureLogin
on: [push]


jobs:

  build-and-deploy:
    runs-on: self-hosted
 
    steps:
    -  uses: actions/checkout@v1     
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
           az vm start -g trimu -n test
